server:
  port: 8000
  host: 0.0.0.0

redis:
  port: 6379

database:
  url: postgresql://postgres:postgres@localhost:5432/mydatabase

test_database:
  url: postgresql://postgres:postgres@localhost:5432/test_database

admin:
  secret: mojkljuc

testing: ${TESTING}
debug: ${DEBUG}

dataset:
  datasets_path: ./data
  max_ticks_in_request: 100
  
  price_multiplier:
    coal: 3000
    uranium: 15000
    biomass: 2900
    gas: 2870
    oil: 2900
    energy: 500

  energy_output_multiplier:
    coal: 15
    uranium: 160
    biomass: 30
    gas: 30
    oil: 30
    geothermal: 3
    wind: 1
    solar: 1
    hydro: 2

  energy_demand_multiplier: 55100

player:
  starting_money: 350000
  max_orders: 10

bots:
  team_name: bots
  team_secret: oiajsdpifjapsndkcapis
  resource_sum: 1000
  default_volume: 250
  min_volume: 200
  max_volume: 6000
  min_price: 1
  max_price: 201
  expiration_ticks: 5
  price_change_coeff: 0.3
  dataset_price_weight: 0.85
  extra_orders: 3
  extra_orders_price_diff: 0.1
  extra_orders_volume_diff: 0.2
  final_volume_multiplier: 1
  final_price_multiplier: 1

max_energy_per_player: 0.2

power_plant:
  resources_per_tick: 1
  price_coeff: 0.5
  sell_coeff: 0.7

  base_prices:
    coal: 302500
    uranium: 9750000
    biomass: 968000
    gas: 970400
    oil: 968000
    geothermal: 450000
    wind: 150000
    solar: 150000
    hydro: 300000
