server:
  port: 8000
  host: 0.0.0.0

datasets_path: ./data

redis:
  port: 6379

database:
  url: postgresql://postgres:postgres@localhost:5432/mydatabase

test_database:
  url: postgresql://postgres:postgres@localhost:5432/test_database

admin:
  secret: mojkljuc

game:
  tick_interval: 1

player:
  starting_money: 15000

bots:
  team_name: bots
  team_secret: oiajsdpifjapsndkcapis
  resource_sum: 1000
  default_volume: 100
  min_volume: 20
  max_volume: 600
  min_price: 1
  max_price: 100
  max_price_change: 20
  expiration_ticks: 5
  price_change_coeff: 0.05
  dataset_price_weight: 0.5

max_energy_per_player: 0.2

power_plant:
  resources_per_tick: 1
  price_coeff: 0.5
  sell_coeff: 0.7

  base_prices:
    coal: 3000
    uranium: 250000
    biomass: 5000
    gas: 7000
    oil: 10000
    geothermal: 25000
    wind: 10000
    solar: 10000
    hydro: 100000

  warmup_coeff:
    coal: 1.06
    uranium: 1.04
    biomass: 1.12
    gas: 1.07
    oil: 1.47
    geothermal: 1.07
    wind: 3
    solar: 3
    hydro: 1.31

  cooldown_coeff:
    coal: 0.84
    uranium: 0.66
    biomass: 0.78
    gas: 0.55
    oil: 0.45
    geothermal: 0.7
    wind: 0.1
    solar: 0.05
    hydro: 0.3

  dataset_rows:
    coal: null
    uranium: null
    biomass: null
    gas: null
    oil: null
    geothermal: geo
    wind: wind
    solar: solar
    hydro: hydro
