server:
  port: 8000
  host: 0.0.0.0

redis:
  port: 6379

database:
  url: postgresql://postgres:postgres@localhost:5432/mydatabase

test_database:
  url: postgresql://postgres:postgres@localhost:5432/test_database

admin:
  secret: mojkljuc

testing: ${TESTING}
debug: ${DEBUG}

dataset:
  datasets_path: ./data
  max_ticks_in_request: 100
  
  price_multiplier:
    coal: 2400
    uranium: 30000
    biomass: 6000
    gas: 6070
    oil: 6000
    energy: 50

  energy_output_multiplier:
    coal: 150
    uranium: 1600
    biomass: 300
    gas: 300
    oil: 300
    geothermal: 30
    wind: 10
    solar: 10
    hydro: 20

  energy_demand_multiplier: 30000

player:
  max_players_per_team: 10
  starting_money: 1500000
  max_orders: 10

bots:
  team_name: bots
  team_secret: oiajsdpifjapsndkcapis
  resource_sum: 1000
  default_volume: 200
  min_volume: 50
  max_volume: 400
  min_price: -100
  max_price: 100
  expiration_ticks: 5
  price_change_coeff: 0.3
  extra_orders: 5
  extra_orders_price_diff: 0.01
  extra_orders_volume_diff: 0.1
  final_volume_multiplier: 1
  final_price_multiplier: 1

max_energy_per_player: 0.2

power_plant:
  resources_per_tick: 1
  price_coeff: 0.5
  sell_coeff: 0.7

  base_prices:
    coal: 302500
    uranium: 9750000
    biomass: 968000
    gas: 970400
    oil: 968000
    geothermal: 400000
    wind: 100000
    solar: 100000
    hydro: 250000
