# Algotrade Docker Compose File for testing and development

version: "3"

services:
  # Postgres service
  # Change the first port number to the port you want to use for the Postgres service
  postgres:
    container_name: algotrade-postgres
    image: postgres:12.1
    restart: unless-stopped
    ports:
      - 7685:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - algotrade-net

  postgres_test:
    container_name: algotrade-postgres-test
    image: postgres:12.1
    restart: unless-stopped
    ports:
      - 7686:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_database
    volumes:
      - "postgres-test-data:/var/lib/postgresql/data"
    networks:
      - algotrade-net

  # Redis service
  # Change the first port number to the port you want to use for the Redis service
  redis:
    container_name: algotrade-redis
    image: redis:latest
    restart: unless-stopped
    command: redis-server --save 10 1 --loglevel warning --requirepass on-resx-pass
    ports:
      - 7687:6379
    networks:
      - algotrade-net
    volumes:
      - "redis-data:/data"

networks:
  algotrade-net:
    external: false
    driver: bridge

volumes:
  postgres-data: {}
  postgres-test-data: {}
  redis-data: {}
